version: "{build}"
image: Visual Studio 2019
environment:
  global:
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
test: off
branches:
  only:
    - master
    - /^release\/.*$/
build_script:
  - cmd: build.cmd
artifacts:
  - path: 'src\SymbolCollector.Android\bin\release\*.apk'
  - path: 'src\SymbolCollector.Console\osx-x64\'
  - path: 'src\SymbolCollector.Console\linux-x64\'
  - path: 'src\SymbolCollector.Console\linux-musl-x64\'
  - path: 'src\SymbolCollector.Console\linux-arm\'
  - path: 'src\SymbolCollector.Server\server\'
on_success:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f '*.cobertura.xml'
